language: node_js
sudo: false
node_js:
  - "10"
  - "9"
  - "8"

install:
  - npm install

script:
  - echo "Skipping tests"

before_deploy:
 - npm install -g vsce
 - vsce package
 - find . -name "hmlr-dev-pack*.vsix" -exec mv '{}' hmlr-dev-pack.vsix

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

